# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: kramdown
disqus: leandroh
google_analytics: leandroh

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: parasitando.me/blog

description: parasitando.me/blog
author:
  name: Leandro "Parazito"
  email: leandroh@gmail.com
  github: leandroh
  twitter: parazito
  #pinterest: asd123
  linkedin: https://br.linkedin.com/pub/leandro-heuert/1/a45/189
  bio: Uma pessoa apaixonada por programação poliglota, padrões de desenvolvimento web, banco de dados e APIs RESTful.
  email_md5: edea60ebe538f3bd0bf2fea687a94a79

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
